# Generated by Django 4.0.4 on 2022-04-22 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answer_created_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answer_updated_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='is_email',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='이메일 수신 여부'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='is_phone',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='문자 메세지 수신 여부'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
