# Generated by Django 4.0.4 on 2022-04-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='category',
            field=models.CharField(choices=[('A', 'category A'), ('B', 'category B'), ('C', 'category C'), ('D', 'category D')], default='others', max_length=256),
        ),
    ]
