# Generated by Django 4.0.4 on 2022-04-22 01:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_inquiry_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='phone_number',
            field=models.CharField(blank=True, help_text='format: 010-1234-1234', max_length=13, null=True, validators=[django.core.validators.RegexValidator('^\\d\\d\\d-\\d\\d\\d\\d-\\d\\d\\d\\d$', message='Wrong format enter')], verbose_name='전화번호'),
        ),
    ]
